config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: { sessions: 'users/sessions', confirmations: 'users/confirmations' }

  mount ShopifyApp::Engine, at: '/shopify'

  namespace :shopify do

    resources :vendor_invites do
      member do
        delete :cancel
      end
    end

    resources :vendors do
      member do
        patch :change_status
      end
    end

    resources :products

    resources :time_slots
    resources :bookings

    resources :payouts do
      member do
        patch :manual_payment
        patch :stripe_payment
      end
    end

    resource :setting

    resource :admin_user_setup, only: %i[show create]
    resource :payment_setup, only: %i[show]

    root :to => 'home#index'
  end

  resource :vendor_invite_wizard do
    get   :set_password
    patch :set_password
    get   :complete_info
    post  :complete_info
    get   :payment_info
  end

  resource :vendor do
    get :dashboard
    get :calendar
    get :bookings
    get :products
    get :orders
    get :payouts
    get :settings
  end

  resource :admin do
    get :dashboard
  end

  get "/stripe/connect/vendor_connect/callback", to: 'stripe#vendor_connect_callback', as: 'stripe_vendor_connect_callback'
  get "/stripe/connect/admin_connect/callback", to: 'stripe#admin_connect_callback', as: 'stripe_admin_connect_callback'


  post "/stripe/account/webhook", to: 'stripe#account_webhook', as: 'stripe_account_webhook'
  post "/stripe/connect/webhook", to: 'stripe#connect_webhook', as: 'stripe_connect_webhook'

  get "/shopify/scripttags/booking.js", to: 'scripttags#booking', as: 'scripttags_booking_script'
  get "/shopify/scripttags/products/:product_id/info.json", to: 'scripttags#product_info', as: 'scripttags_product_info'
  get "/shopify/scripttags/client_calendar.js", to: 'scripttags#client_calendar', as: 'scripttags_client_calendar_script'
  get "/shopify/scripttags/bookings.json", to: 'scripttags#bookings', as: 'scripttags_bookings_script'

  resources :time_slots

  resources :products do
    get :new
    get :show
    post :create
    patch :update
  end

  resources :orders do
    
  end

  root :to => 'home#index'
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  #--------------------------------------------------------------------
  # Constants
  #--------------------------------------------------------------------
  ACTIVE_STATUS = 'Active'

  #--------------------------------------------------------------------
  # Attributes
  #--------------------------------------------------------------------
  alias_attribute :name, :business_name

  #--------------------------------------------------------------------
  # Associations
  #--------------------------------------------------------------------
  belongs_to :shop
  belongs_to :user, optional: true
  has_many :products
  has_many :bookings
  has_many :payouts

  #--------------------------------------------------------------------
  # Validations
  #--------------------------------------------------------------------
  validates :email, presence: true, 
                    format: { with: URI::MailTo::EMAIL_REGEXP }, 
                    uniqueness: {scope: 'shop_id'}

  validates :business_name, presence: true, uniqueness: {scope: 'shop_id', allow_blank: true}                   
  validates :tax_id, presence: true                   
  validates :poc_first_name, presence: true                   
  validates :poc_last_name, presence: true                   
  validates :phone_number, presence: true
  validates :status, presence: true

  #--------------------------------------------------------------------
  # Scopes
  #--------------------------------------------------------------------
  scope :active, -> { where(:status => ACTIVE_STATUS) }

  #--------------------------------------------------------------------
  # Concerns
  #--------------------------------------------------------------------
  include Concerns::StripeConcern
  include Vendor::ReportDataGeneratorConcern

  #--------------------------------------------------------------------
  # Methods
  #--------------------------------------------------------------------

  def shopify_orders
    self.bookings.map { |booking| booking.shopify_order }
  end

  def unfulfilled_shopify_orders
    shopify_orders.select { |o| o.fulfillment_status.blank? }
  end

  def change_status
    if self.status == "Active"
      self.status = "Inactive"
      self.save
    else
      self.status = "Active"
      self.save
    end
  end
end

app/controllers/shopify/admin_user_setups_controller.rb
class Shopify::AdminUserSetupsController < Shopify::BaseController

  skip_before_action :check_prerequisites!

  def show
    @user = current_shop.users.build({
      email: current_shop.shopify_session { ShopifyAPI::Shop.current.email },
      role: User::ADMIN_ROLE
    }) 
  end

  def create
    @user = current_shop.users.build({
      email: current_shop.shopify_session { ShopifyAPI::Shop.current.email },
      role: User::ADMIN_ROLE,
      password: user_params[:password],
      password_confirmation: user_params[:password_confirmation]    
    })
    @user.validate_password!
    @user.skip_confirmation!
    if @user.save
      current_shop.update_column(:admin_user_id, @user.id)
      redirect_to shopify_root_path
    else
      render :show
    end 
  end

  private

    def user_params
      params.require(:user).permit(
        :password,
        :password_confirmation
      )
    end
end

app/controllers/shopify/base_controller.rb
class Shopify::BaseController < ShopifyApp::AuthenticatedController

  before_action :check_prerequisites!

  helper :all
  helper_method :current_shop

  protected

    def current_shop
      Shop.find_by_shopify_domain!(current_shopify_domain)
    end

  private

    def check_prerequisites!
      if current_shop.has_no_admin_user?
        redirect_to shopify_admin_user_setup_path
      elsif not current_shop.has_payment_info?
        redirect_to shopify_payment_setup_path
      end
    end
end

app/controllers/shopify/bookings_controller.rb
class Shopify::BookingsController < Shopify::BaseController

  def index
    @bookings = current_shop.bookings
  end
end

app/controllers/shopify/home_controller.rb
class Shopify::HomeController < Shopify::BaseController

  def index
  	@active_vendors = current_shop.vendors.active
  	@new_time_slot = current_shop.time_slots.build
    @new_product = current_shop.products.build
    @vendor_invites = current_shop.vendor_invites
    @vendors = current_shop.vendors
    @products = current_shop.products
    @unbooked_shopify_products = current_shop.unbooked_shopify_products
    @booked_shopify_products = current_shop.booked_shopify_products
    @payouts = current_shop.payouts.includes(:vendor)

    @sales_total = current_shop.payouts.sum(:amount_sold)
    @commission_total = current_shop.payouts.sum(:amount_commissions_earned)

    @payouts_unpaid = current_shop.payouts.unpaid.sum(:amount_to_be_paid_out)
    @payouts_paid = current_shop.payouts.paid.sum(:amount_to_be_paid_out)
    @payouts_total = current_shop.payouts.sum(:amount_to_be_paid_out)

    @product_sales_title = "#{Time.zone.now.strftime('%B %Y')} Product Sales"
    @product_sales_report_data = current_shop.generate_product_sales_report_data

    @product_commissions_earned_title = "#{Time.zone.now.strftime('%B %Y')} Product Commissions Earned"
    @product_commissions_earned_report_data = current_shop.generate_product_commissions_earned_report_data
  end
end

app/controllers/shopify/payment_setups_controller.rb
class Shopify::PaymentSetupsController < Shopify::BaseController

  skip_before_action :check_prerequisites!

  def show
  end

  private
end

app/controllers/shopify/payouts_controller.rb
class Shopify::PayoutsController < Shopify::BaseController
	  
  before_action :set_payout, only: %i[manual_payment stripe_payment]

  def manual_payment
    @payout.manual_payment!
    respond_to do |format|
      format.js
    end
  end

  def stripe_payment
    @payout.stripe_payment!
    respond_to do |format|
      format.js
    end
  end

  private

    def set_payout
      @payout = current_shop.payouts.find(params[:id])
    end
end

app/controllers/shopify/products_controller.rb
class Shopify::ProductsController < Shopify::BaseController
	
  before_action :set_product, only: %i[show edit update destroy]
  before_action :set_shopify_product, only: %i[new create]

  def new
    @product = current_shop.products.build
    @product.set_shopify_product!(@shopify_product)
  end

	def create
		@product = current_shop.products.build(product_params)
    @product.set_shopify_product!(@shopify_product)
		if @product.save
			redirect_to shopify_root_path(tab: 'products')
			flash[:notice] = 'Product was successfully added'
		else
			render :new
		end
	end

  def show
    render :edit
  end

  def edit

  end

  def update
    if @product.update_attributes(product_params)
      redirect_to shopify_root_path(tab: 'products')
      flash[:notice] = 'Product was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy!
    respond_to do |format|
      format.js
    end
  end

	private

    def set_product
      @product = current_shop.products.find(params[:id])
    end
  
  	def product_params
  		params.require(:product).permit(
        :vendor_id,
        :title,
  			:cost_of_goods,
  			:minimum_commission_per_product,
  			:commission_structure_type,
        :is_bookable,
        time_slot_ids: []
  		)
  	end		

    def shopify_product_id
      params[:shopify_product_id]
    end

    def set_shopify_product
      @shopify_product = current_shop.find_shopify_product(shopify_product_id)
    end
end

app/controllers/shopify/settings_controller.rb
class Shopify::SettingsController < Shopify::BaseController

	def update
		@setting = current_shop.setting
		if @setting.update_attributes(setting_params)
			redirect_to shopify_root_path('tab' => 'settings')
			flash.notice = 'Settings successfully updated'
		end
	end

	private 

	  def setting_params
		  params.require(:setting).permit(
			  :shop_id,
			  :minimum_commission_per_product,
			  :structure_type
		  )
	  end
end

app/controllers/shopify/time_slots_controller.rb
class Shopify::TimeSlotsController < Shopify::BaseController

  before_action :set_time_slot, only: %i[show edit update destroy]

  def index
    @time_slots = current_shop.time_slots

    respond_to do |format|
      format.json
    end
  end

  def new
    @time_slot = current_shop.time_slots.build
  end

  def create
    @time_slot = current_shop.time_slots.build(time_slot_params)
    if @time_slot.save
      flash.notice = 'Timeslot was successfuly created'
      redirect_to shopify_root_path 'tab' => 'calendar'
    else
      render :new
    end
  end

  def show
    redirect_to edit_shopify_time_slot_path(@time_slot)
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    if @time_slot.update_attributes(time_slot_params)
      flash.notice = 'Timeslot was successfuly updated'
      redirect_to shopify_root_path 'tab' => 'calendar'
    else
      render :edit
    end
  end

  def destroy
    @time_slot.destroy!
    flash.notice = 'Timeslot was successfuly destroyed'
    redirect_to shopify_root_path 'tab' => 'calendar'
  end

  private

    def set_time_slot
      @time_slot = current_shop.time_slots.find(params[:id])
    end

    def time_slot_params
      params.require(:time_slot).permit(
        :description,
        :start_date,
        :start_time,
        :end_date,
        :end_time
        #:is_all_day
      )
    end
end

app/controllers/shopify/vendor_invites_controller.rb
class Shopify::VendorInvitesController < Shopify::BaseController

  before_action :set_vendor_invite, only: %w[cancel]

  def index
    @vendor_invites = current_shop.vendor_invites
  end

  def new
    @vendor_invite = current_shop.vendor_invites.build
  end

  def create
    @vendor_invite = current_shop.vendor_invites.build(vendor_invite_params)
    if @vendor_invite.save
      redirect_to shopify_root_path('tab' => 'vendor_invites')
      flash.notice = "Invitation for vendor was sent to #{@vendor_invite.email}."
    else
      render :new
    end
  end

  def cancel
    if @vendor_invite.can_cancel?
      @vendor_invite.cancel!
      @vendor_invites = current_shop.vendor_invites
      respond_to do |format|
        format.js
      end
    else
      @vendor_invites = current_shop.vendor_invites
      respond_to do |format|
        format.js
      end
    end
  end

  private

    def set_vendor_invite
      @vendor_invite = current_shop.vendor_invites.find(params[:id])
    end

    def vendor_invite_params
      params.require(:vendor_invite).permit(
        :email
      )
    end
end

app/controllers/shopify/vendors_controller.rb
class Shopify::VendorsController < Shopify::BaseController

  def index
    @vendors = current_shop.vendors
  end

  def new
    @vendor = current_shop.vendors.build
  end

  def create
    @vendor = current_shop.vendors.build(vendor_params)
    if @vendor.save
      redirect_to shopify_root_path'tab' => 'vendors'
      flash.notice = 'Vendor was successfuly created'
    else
      render :new
    end
  end

  def change_status
    @vendor = Vendor.find_by_id(params[:id].to_i)
    @vendor.change_status
    redirect_to shopify_root_path'tab' => 'vendors'
  end

  private

    def vendor_params
      params.require(:vendor).permit(
        :business_name,
        :poc_first_name,
        :poc_last_name,
        :phone_number,
        :email,
        :tax_id,
        :address
      )
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user_in_vendor_role!

  def show
    redirect_to dashboard_vendor_path
  end

  def dashboard
    @unpaid_payouts = current_vendor.payouts.unpaid
    @products = current_vendor.products
    @unfulfilled_orders_count = current_vendor.unfulfilled_shopify_orders.length
    @orders_count = current_vendor.shopify_orders.length
    @products_count = @products.length
    @payouts_paid = ActionController::Base.helpers.number_to_currency(current_vendor.payouts.paid.sum(:amount_to_be_paid_out).round(2))
    @payouts_receivable = ActionController::Base.helpers.number_to_currency(current_vendor.payouts.unpaid.sum(:amount_to_be_paid_out).round(2))
    @total_payouts = ActionController::Base.helpers.number_to_currency(current_vendor.payouts.sum(:amount_to_be_paid_out).round(2))
    @payouts_report_title = Time.zone.now.strftime('%B %Y')
    @payouts_report_data = current_vendor.generate_payouts_report_data
  end

  def calendar

  end

  def bookings
    @bookings = current_vendor.bookings
    respond_to do |format|
      format.json
    end
  end

  def products
    @products = current_vendor.products
  end
  
  def orders
    @orders = current_vendor.shopify_orders
  end
  
  def payouts
    @payouts = current_vendor.payouts
  end
  
  def settings

  end
end

app/helpers/shopify/payouts_helper.rb
module Shopify::PayoutsHelper
end

app/helpers/shopify/products_helper.rb
module Shopify::ProductsHelper
end

app/helpers/shopify/settings_helper.rb
module Shopify::SettingsHelper
end

app/helpers/vendor_helper.rb
module VendorHelper

  def vendor_sidebar_active_class(section_name)
    if controller_name == 'vendors' and action_name == section_name.to_s
      'active'
    else
      ''
    end
  end
end

app/views/shopify/vendors/_form.html.haml
= form_for (local_assigns[:vendor] || @vendor || Vendor.new), url: local_assigns[:form_url] || shopify_vendors_path, html: {'id' => 'new-vendor-form'} do |f|
  
  .form-group{'class' => "#{f.object.errors[:business_name].present? ? 'has-error' : ''}"}
    = f.label :business_name, 'Business name', 'class' => ''
    = f.text_field :business_name, 'class' => 'form-control', 'autofocus' => true
    - if f.object.errors[:business_name].present?
      %span.help-block= f.object.errors[:business_name].join(', ')

  .form-group{'class' => "#{f.object.errors[:poc_first_name].present? ? 'has-error' : ''}"}
    = f.label :poc_first_name, 'First name', 'class' => ''
    = f.text_field :poc_first_name, 'class' => 'form-control'
    - if f.object.errors[:poc_first_name].present?
      %span.help-block= f.object.errors[:poc_first_name].join(', ')

  .form-group{'class' => "#{f.object.errors[:poc_last_name].present? ? 'has-error' : ''}"}
    = f.label :poc_last_name, 'Last name', 'class' => ''
    = f.text_field :poc_last_name, 'class' => 'form-control'
    - if f.object.errors[:poc_last_name].present?
      %span.help-block= f.object.errors[:poc_last_name].join(', ')

  .form-group{'class' => "#{f.object.errors[:phone_number].present? ? 'has-error' : ''}"}
    = f.label :phone_number, 'Phone number', 'class' => ''
    = f.text_field :phone_number, 'class' => 'form-control'
    - if f.object.errors[:phone_number].present?
      %span.help-block= f.object.errors[:phone_number].join(', ')

  .form-group{'class' => "#{f.object.errors[:email].present? ? 'has-error' : ''}"}
    = f.label :email, 'Email', 'class' => ''
    = f.text_field :email, 'class' => 'form-control', 'readonly' => (!f.object.new_record? || local_assigns[:make_readonly_email])
    - if f.object.errors[:email].present?
      %span.help-block= f.object.errors[:email].join(', ')

  .form-group{'class' => "#{f.object.errors[:tax_id].present? ? 'has-error' : ''}"}
    = f.label :tax_id, 'Tax ID', 'class' => ''
    = f.text_field :tax_id, 'class' => 'form-control'
    - if f.object.errors[:tax_id].present?
      %span.help-block= f.object.errors[:tax_id].join(', ')
  
  .form-group{'class' => "#{f.object.errors[:address].present? ? 'has-error' : ''}"}
    = f.label :address, 'Address', 'class' => ''
    = f.text_area :address, 'class' => 'form-control'
    - if f.object.errors[:address].present?
      %span.help-block= f.object.errors[:address].join(', ')

  - if local_assigns[:show_submit]
    .form-commands
      = f.submit 'Save', 'class' => 'btn btn-primary btn-lg'

app/views/shopify/vendors/_new_dialog.html.haml
.modal.fade{'id' => 'new-vendor-dialog', 'role' => 'dialog', :tabindex => "-1"}
  .modal-dialog{'role' => 'document'}
    .modal-content
      .modal-header
        %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', 'type' => 'button'}
          %span{'aria-hidden' => 'true'} ×
        %h4.modal-title New Vendor
      .modal-body
        = render partial: 'shopify/vendors/form'

      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary.save{:type => "button"} Save changes

- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      $('#new-vendor-dialog').on('shown.bs.modal', function (e) {
        
        var $dialog = $(this);
        var $form = $dialog.find('#new-vendor-form');
        var $saveButton = $dialog.find('.modal-footer button.save');
        $saveButton.on('click', function(e) {
          e.stopPropagation();
          e.preventDefault();
          $form.submit();
          $saveButton.html('Saving...');
          $saveButton.attr('disabled', 'disabled');
        });
        $form.find('input[name="vendor[name]"]').focus();
      });
    })(window);

app/views/shopify/vendors/_table.html.haml
- unless vendors.present?
  %p
    You have no vendors yet, Create new #{link_to('here', new_shopify_vendor_path)}.
- else
  %table.table.table-hover.table-striped
    %thead
      %th ID
      %th Name
      %th Created At
      %th Status
      %th Options
    %tbody
      - vendors.each do |vendor|
        %tr
          %td= vendor.id
          %td= vendor.name
          %td= vendor.created_at.strftime('%b %-d, %Y')
          %td= vendor.status
          - if (vendor.status == "Active")
            %td= link_to "Deactivate", change_status_shopify_vendor_path(vendor.id), method: "patch"
          - else
            %td= link_to "Activate", change_status_shopify_vendor_path(vendor.id), method: "patch"

app/views/shopify/vendors/index.html.haml
- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      ShopifyApp.ready(function() {

        ShopifyApp.Bar.initialize({ 
          title: 'Vendors',
          breadcrumb: {
            label: "Home",
            href: "#{shopify_root_path}",
            target: 'app',
            loading: false
          }
        });
      });


    })(window);

.Polaris-Page
  .Polaris-Page__Header.Polaris-Page__Header--hasBreadcrumbs.Polaris-Page__Header--hasSecondaryActions.Polaris-Page__Header--hasSeparator
    .Polaris-Page__MainContent
      
      .Polaris-Page__TitleAndActions
        .Polaris-Page__Title
          %h1.Polaris-DisplayText.Polaris-DisplayText--sizeLarge 
            Vendors
      
      .Polaris-Page__PrimaryAction
        .btn-group
          = link_to 'Invite Vendor', new_shopify_vendor_invite_path, 'class' => 'btn btn-primary'
            
          %button{'type' => 'button', 'class' => 'btn btn-primary dropdown-toggle', 'data-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false'}           
            %span.caret
            %span.sr-only
              More Actions
          %ul.dropdown-menu
            %li
              = link_to 'Create New Vendor', new_shopify_vendor_path

  .Polaris-Page__Content
    .Polaris-Layout
      .Polaris-Layout__Section
        .container-fluid
          = render partial: 'shopify/vendors/table', locals: {vendors: @vendors}

app/views/shopify/vendors/new.html.haml
- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      ShopifyApp.ready(function() {

        ShopifyApp.Bar.initialize({ 
          title: 'New Vendor',
          breadcrumb: {
            label: "Home",
            href: "#{shopify_root_path}",
            target: 'app',
            loading: false
          } 
        });

        $('#save-vendor-button').on('click', function(e) {
          e.preventDefault();
          e.stopPropagation();

          var $button = $(this);
          $button.html('Saving...');
          $button.attr('disabled', 'disabled');

          var $form = $('#new-vendor-form');
          $form.submit();
        });
      });


    })(window);

.Polaris-Page
  .Polaris-Page__Header.Polaris-Page__Header--hasBreadcrumbs.Polaris-Page__Header--hasSecondaryActions.Polaris-Page__Header--hasSeparator
    .Polaris-Page__MainContent
      
      .Polaris-Page__TitleAndActions
        .Polaris-Page__Title
          %h1.Polaris-DisplayText.Polaris-DisplayText--sizeLarge 
            New Vendor
      
      .Polaris-Page__PrimaryAction
        .btn-group
          %button{'type' => 'button', 'class' => 'btn btn-primary', 'id' => 'save-vendor-button'}
            Save

  .Polaris-Page__Content
    .Polaris-Layout
      .Polaris-Layout__Section
        .container-fluid
          = render partial: 'shopify/vendors/form'