config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: { sessions: 'users/sessions', confirmations: 'users/confirmations' }

  mount ShopifyApp::Engine, at: '/shopify'

  namespace :shopify do

    resources :vendor_invites do
      member do
        delete :cancel
      end
    end

    resources :vendors do
      member do
        patch :change_status
      end
    end

    resources :products

    resources :time_slots
    resources :bookings

    resources :payouts do
      member do
        patch :manual_payment
        patch :stripe_payment
      end
    end

    resource :setting

    resource :admin_user_setup, only: %i[show create]
    resource :payment_setup, only: %i[show]

    root :to => 'home#index'
  end

  resource :vendor_invite_wizard do
    get   :set_password
    patch :set_password
    get   :complete_info
    post  :complete_info
    get   :payment_info
  end

  resource :vendor do
    get :dashboard
    get :calendar
    get :bookings
    get :products
    get :orders
    get :payouts
    get :settings
  end

  resource :admin do
    get :dashboard
  end

  get "/stripe/connect/vendor_connect/callback", to: 'stripe#vendor_connect_callback', as: 'stripe_vendor_connect_callback'
  get "/stripe/connect/admin_connect/callback", to: 'stripe#admin_connect_callback', as: 'stripe_admin_connect_callback'


  post "/stripe/account/webhook", to: 'stripe#account_webhook', as: 'stripe_account_webhook'
  post "/stripe/connect/webhook", to: 'stripe#connect_webhook', as: 'stripe_connect_webhook'

  get "/shopify/scripttags/booking.js", to: 'scripttags#booking', as: 'scripttags_booking_script'
  get "/shopify/scripttags/products/:product_id/info.json", to: 'scripttags#product_info', as: 'scripttags_product_info'
  get "/shopify/scripttags/client_calendar.js", to: 'scripttags#client_calendar', as: 'scripttags_client_calendar_script'
  get "/shopify/scripttags/bookings.json", to: 'scripttags#bookings', as: 'scripttags_bookings_script'

  resources :time_slots

  resources :products do
    get :new
    get :show
    post :create
    patch :update
  end

  resources :orders do
    
  end

  root :to => 'home#index'
end

app/models/product/commission_splitting_concern.rb
module Product::CommissionSplittingConcern
  extend ActiveSupport::Concern

  #--------------------------------------------------------------------
  # Methods
  #--------------------------------------------------------------------
  def calculate_commission_split_for_amount(amount)
    amount_commissions_earned = 0.00  
    amount_to_be_paid_out = 0.00 
    if commission_structure_type_amount?
      amount_to_be_paid_out = amount - minimum_commission_per_product
      amount_commissions_earned = amount - amount_to_be_paid_out
    elsif commission_structure_type_percentage?
      percentage = minimum_commission_per_product / 100.00
      amount_to_be_paid_out = amount - (amount * percentage)
      amount_commissions_earned = amount - amount_to_be_paid_out
    else
      raise "Invalid product commision structure type"
    end
    [amount_commissions_earned, amount_to_be_paid_out]
  end
end

app/models/product/shopify_concern.rb
module Product::ShopifyConcern
  extend ActiveSupport::Concern

  #--------------------------------------------------------------------
  # Methods
  #--------------------------------------------------------------------
  def shopify_product
    @shopify_product ||= self.shop.shopify_session { ShopifyAPI::Product.find(self.shopify_id) }
    ShopifyProduct.new(shop, @shopify_product)
  rescue
    nil
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base

  #--------------------------------------------------------------------
  # Modules Included
  #--------------------------------------------------------------------
  include ShopifyApp::SessionStorage

  #--------------------------------------------------------------------
  # Associations
  #--------------------------------------------------------------------
  belongs_to :admin_user, class_name: User.name, optional: true

  has_one :setting, dependent: :destroy

  has_many :users, dependent: :destroy
  has_many :vendor_invites, dependent: :destroy
  has_many :vendors
  has_many :time_slots, dependent: :destroy
  has_many :products
  has_many :payouts
  has_many :bookings

  #--------------------------------------------------------------------
  # Callbacks
  #--------------------------------------------------------------------
  before_create :setup_setting

  #--------------------------------------------------------------------
  # Concerns
  #--------------------------------------------------------------------
  include Shop::PayoutProcessingConcern
  include Shop::BookingProcessingConcern
  include Shop::ReportDataGeneratorConcern

  #--------------------------------------------------------------------
  # Delegations
  #--------------------------------------------------------------------
  delegate :has_payment_info?, to: :setting

  #--------------------------------------------------------------------
  # Methods
  #--------------------------------------------------------------------

  def shopify_session(&block)
    ShopifyAPI::Session.temp(self.shopify_domain, self.shopify_token, &block)
  end

  def name
    @shop_name ||= shopify_session { ShopifyAPI::Shop.current.name }
  end

  def shopify_products
    shopify_session { ShopifyAPI::Product.all.to_a
      .map { |p| ShopifyProduct.new(self, p) } }
  end

  def booked_shopify_products
    shopify_products.select { |p| p.is_booked? }
  end

  def unbooked_shopify_products
    shopify_products.select { |p| not p.is_booked? }
  end

  def find_shopify_product(id)
    shopify_product = shopify_session { ShopifyAPI::Product.find(id) }
    ShopifyProduct.new(self, shopify_product)
  end

  def has_admin_user?
    self.admin_user.present?
  end

  def has_no_admin_user?
    not has_admin_user?
  end

  private

    def setup_setting
      self.setting = build_setting
      self.setting.minimum_commission_per_product = 0
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_product, only: %i[edit update destroy]
  
  def new
    @product = current_shop.products.build
  end

  def create
    @product = current_shop.products.build(product_params)
    if @product.save
      redirect_to '/vendor/products'
      flash[:notice] = 'Product was successfully created'
    else
      render :new
    end
  end

  def show
    render :edit
  end

  def edit
    @product = scope.products.find(params[:id])
  end

  def update
    @product = scope.products.find(params[:id]).first()
    if @product.update_attributes(product_params)
      redirect_to '/vendor/products'
      flash[:notice] = 'Product was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @product = scope.products.find(params[:id])
    if @product.destroy!
      redirect_to '/vendor/products'
      flash[:notice] = 'Product was successfully deleted'
    end
  end

  private

    def scope
      current_vendor || current_shop
    end

    def set_product
      scope.products.find(params[:id])
    end 

    def product_params
      params.require(:product).permit(
        :vendor_id,
        :title,
        :body_html,
        :price,
        :minimum_commission_per_product,
        :commission_structure_type
      )
    end

end

app/controllers/shopify/admin_user_setups_controller.rb
class Shopify::AdminUserSetupsController < Shopify::BaseController

  skip_before_action :check_prerequisites!

  def show
    @user = current_shop.users.build({
      email: current_shop.shopify_session { ShopifyAPI::Shop.current.email },
      role: User::ADMIN_ROLE
    }) 
  end

  def create
    @user = current_shop.users.build({
      email: current_shop.shopify_session { ShopifyAPI::Shop.current.email },
      role: User::ADMIN_ROLE,
      password: user_params[:password],
      password_confirmation: user_params[:password_confirmation]    
    })
    @user.validate_password!
    @user.skip_confirmation!
    if @user.save
      current_shop.update_column(:admin_user_id, @user.id)
      redirect_to shopify_root_path
    else
      render :show
    end 
  end

  private

    def user_params
      params.require(:user).permit(
        :password,
        :password_confirmation
      )
    end
end

app/controllers/shopify/base_controller.rb
class Shopify::BaseController < ShopifyApp::AuthenticatedController

  before_action :check_prerequisites!

  helper :all
  helper_method :current_shop

  protected

    def current_shop
      Shop.find_by_shopify_domain!(current_shopify_domain)
    end

  private

    def check_prerequisites!
      if current_shop.has_no_admin_user?
        redirect_to shopify_admin_user_setup_path
      elsif not current_shop.has_payment_info?
        redirect_to shopify_payment_setup_path
      end
    end
end

app/controllers/shopify/bookings_controller.rb
class Shopify::BookingsController < Shopify::BaseController

  def index
    @bookings = current_shop.bookings
  end
end

app/controllers/shopify/home_controller.rb
class Shopify::HomeController < Shopify::BaseController

  def index
  	@active_vendors = current_shop.vendors.active
  	@new_time_slot = current_shop.time_slots.build
    @new_product = current_shop.products.build
    @vendor_invites = current_shop.vendor_invites
    @vendors = current_shop.vendors
    @products = current_shop.products
    @unbooked_shopify_products = current_shop.unbooked_shopify_products
    @booked_shopify_products = current_shop.booked_shopify_products
    @payouts = current_shop.payouts.includes(:vendor)

    @sales_total = current_shop.payouts.sum(:amount_sold)
    @commission_total = current_shop.payouts.sum(:amount_commissions_earned)

    @payouts_unpaid = current_shop.payouts.unpaid.sum(:amount_to_be_paid_out)
    @payouts_paid = current_shop.payouts.paid.sum(:amount_to_be_paid_out)
    @payouts_total = current_shop.payouts.sum(:amount_to_be_paid_out)

    @product_sales_title = "#{Time.zone.now.strftime('%B %Y')} Product Sales"
    @product_sales_report_data = current_shop.generate_product_sales_report_data

    @product_commissions_earned_title = "#{Time.zone.now.strftime('%B %Y')} Product Commissions Earned"
    @product_commissions_earned_report_data = current_shop.generate_product_commissions_earned_report_data
  end
end

app/controllers/shopify/payment_setups_controller.rb
class Shopify::PaymentSetupsController < Shopify::BaseController

  skip_before_action :check_prerequisites!

  def show
  end

  private
end

app/controllers/shopify/payouts_controller.rb
class Shopify::PayoutsController < Shopify::BaseController
	  
  before_action :set_payout, only: %i[manual_payment stripe_payment]

  def manual_payment
    @payout.manual_payment!
    respond_to do |format|
      format.js
    end
  end

  def stripe_payment
    @payout.stripe_payment!
    respond_to do |format|
      format.js
    end
  end

  private

    def set_payout
      @payout = current_shop.payouts.find(params[:id])
    end
end

app/controllers/shopify/products_controller.rb
class Shopify::ProductsController < Shopify::BaseController
	
  before_action :set_product, only: %i[show edit update destroy]
  before_action :set_shopify_product, only: %i[new create]

  def new
    @product = current_shop.products.build
    @product.set_shopify_product!(@shopify_product)
  end

	def create
		@product = current_shop.products.build(product_params)
    @product.set_shopify_product!(@shopify_product)
		if @product.save
			redirect_to shopify_root_path(tab: 'products')
			flash[:notice] = 'Product was successfully added'
		else
			render :new
		end
	end

  def show
    render :edit
  end

  def edit

  end

  def update
    if @product.update_attributes(product_params)
      redirect_to shopify_root_path(tab: 'products')
      flash[:notice] = 'Product was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy!
    respond_to do |format|
      format.js
    end
  end

	private

    def set_product
      @product = current_shop.products.find(params[:id])
    end
  
  	def product_params
  		params.require(:product).permit(
        :vendor_id,
        :title,
  			:cost_of_goods,
  			:minimum_commission_per_product,
  			:commission_structure_type,
        :is_bookable,
        time_slot_ids: []
  		)
  	end		

    def shopify_product_id
      params[:shopify_product_id]
    end

    def set_shopify_product
      @shopify_product = current_shop.find_shopify_product(shopify_product_id)
    end
end

app/controllers/shopify/settings_controller.rb
class Shopify::SettingsController < Shopify::BaseController

	def update
		@setting = current_shop.setting
		if @setting.update_attributes(setting_params)
			redirect_to shopify_root_path('tab' => 'settings')
			flash.notice = 'Settings successfully updated'
		end
	end

	private 

	  def setting_params
		  params.require(:setting).permit(
			  :shop_id,
			  :minimum_commission_per_product,
			  :structure_type
		  )
	  end
end

app/controllers/shopify/time_slots_controller.rb
class Shopify::TimeSlotsController < Shopify::BaseController

  before_action :set_time_slot, only: %i[show edit update destroy]

  def index
    @time_slots = current_shop.time_slots

    respond_to do |format|
      format.json
    end
  end

  def new
    @time_slot = current_shop.time_slots.build
  end

  def create
    @time_slot = current_shop.time_slots.build(time_slot_params)
    if @time_slot.save
      flash.notice = 'Timeslot was successfuly created'
      redirect_to shopify_root_path 'tab' => 'calendar'
    else
      render :new
    end
  end

  def show
    redirect_to edit_shopify_time_slot_path(@time_slot)
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    if @time_slot.update_attributes(time_slot_params)
      flash.notice = 'Timeslot was successfuly updated'
      redirect_to shopify_root_path 'tab' => 'calendar'
    else
      render :edit
    end
  end

  def destroy
    @time_slot.destroy!
    flash.notice = 'Timeslot was successfuly destroyed'
    redirect_to shopify_root_path 'tab' => 'calendar'
  end

  private

    def set_time_slot
      @time_slot = current_shop.time_slots.find(params[:id])
    end

    def time_slot_params
      params.require(:time_slot).permit(
        :description,
        :start_date,
        :start_time,
        :end_date,
        :end_time
        #:is_all_day
      )
    end
end

app/controllers/shopify/vendor_invites_controller.rb
class Shopify::VendorInvitesController < Shopify::BaseController

  before_action :set_vendor_invite, only: %w[cancel]

  def index
    @vendor_invites = current_shop.vendor_invites
  end

  def new
    @vendor_invite = current_shop.vendor_invites.build
  end

  def create
    @vendor_invite = current_shop.vendor_invites.build(vendor_invite_params)
    if @vendor_invite.save
      redirect_to shopify_root_path('tab' => 'vendor_invites')
      flash.notice = "Invitation for vendor was sent to #{@vendor_invite.email}."
    else
      render :new
    end
  end

  def cancel
    if @vendor_invite.can_cancel?
      @vendor_invite.cancel!
      @vendor_invites = current_shop.vendor_invites
      respond_to do |format|
        format.js
      end
    else
      @vendor_invites = current_shop.vendor_invites
      respond_to do |format|
        format.js
      end
    end
  end

  private

    def set_vendor_invite
      @vendor_invite = current_shop.vendor_invites.find(params[:id])
    end

    def vendor_invite_params
      params.require(:vendor_invite).permit(
        :email
      )
    end
end

app/controllers/shopify/vendors_controller.rb
class Shopify::VendorsController < Shopify::BaseController

  def index
    @vendors = current_shop.vendors
  end

  def new
    @vendor = current_shop.vendors.build
  end

  def create
    @vendor = current_shop.vendors.build(vendor_params)
    if @vendor.save
      redirect_to shopify_root_path'tab' => 'vendors'
      flash.notice = 'Vendor was successfuly created'
    else
      render :new
    end
  end

  def change_status
    @vendor = Vendor.find_by_id(params[:id].to_i)
    @vendor.change_status
    redirect_to shopify_root_path'tab' => 'vendors'
  end

  private

    def vendor_params
      params.require(:vendor).permit(
        :business_name,
        :poc_first_name,
        :poc_last_name,
        :phone_number,
        :email,
        :tax_id,
        :address
      )
    end
end

app/helpers/shopify/payouts_helper.rb
module Shopify::PayoutsHelper
end

app/helpers/shopify/products_helper.rb
module Shopify::ProductsHelper
end

app/helpers/shopify/settings_helper.rb
module Shopify::SettingsHelper
end

app/views/shopify/products/_booked_table.html.haml
#shopify-products-table-section
  - unless shopify_products.present?
    %p
      You have no products added yet.
  - else
    %table.table.table-hover.table-striped{'id' => 'booked-products-table'}
      %thead
        %th Title
        %th Cost of Goods
        %th Commission 
        %th Vendor
        %th Vendor Inventory
        %th Is Bookable?
        %th
      %tbody
        - shopify_products.each do |shopify_product|
          %tr{'data-id' => shopify_product.product.id}
            %td= shopify_product.title
            %td= "#{shopify_product.product.cost_of_goods} USD"
            %td= shopify_product.product.commision_display
            %td= shopify_product.product.vendor.business_name
            %td= shopify_product.product.inventory_quantity
            %td= shopify_product.product.is_bookable? ? 'yes' : 'no'
            %td
              .commands
                = link_to 'Edit', edit_shopify_product_path(shopify_product.product)
                |
                = link_to 'Remove', shopify_product_path(shopify_product.product, format: :js), remote: true, method: :delete, data: {confirm: 'Are you sure you want to remove this product from Added?'}

app/views/shopify/products/_index.html.haml
- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      ShopifyApp.ready(function() {

        ShopifyApp.Bar.initialize({ 
          title: 'Products',
          breadcrumb: {
            label: "Home",
            href: "#{shopify_root_path}",
            target: 'app',
            loading: false
          }
        });
      });


    })(window);

= render partial: 'shopify/products/table', locals: {products: @products}    

app/views/shopify/products/_new_dialog.html.haml
.modal.fade{'id' => 'new-product-dialog', 'role' => 'dialog', :tabindex => "-1"}
  .modal-dialog{'role' => 'document'}
    .modal-content
      .modal-header
        %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', 'type' => 'button'}
          %span{'aria-hidden' => 'true'} ×
        %h4.modal-title New Product
      .modal-body
        = render partial: 'shopify/products/form', locals: {product: @new_product, form_url: shopify_products_path, form_html_id: 'new-product-form'}

      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary.save{:type => "button"} Save changes

- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      $('#new-product-dialog').on('shown.bs.modal', function (e) {
        
        var $dialog = $(this);
        var $form = $dialog.find('#new-product-form');
        var $saveButton = $dialog.find('.modal-footer button.save');
        $saveButton.on('click', function(e) {
          e.stopPropagation();
          e.preventDefault();
          $form.submit();
          $saveButton.html('Saving...');
          $saveButton.attr('disabled', 'disabled');
        });
        $form.find('input[name="product[description]"]').focus();
      });
    })(window);

app/views/shopify/products/_table.html.haml
#products-table-section
  - unless products.present?
    %p
      You have not created a product yet.
  - else
    %table.table.table-hover.table-striped{'id' => 'products-table'}
      %thead
        %th ID
        %th Title
        %th Price
        %th Created At
        %th Vendor
        %th Options
      %tbody
        - products.each do |product|
          %tr{'data-product-id' => product.id}
            %td= product.id
            %td= product.title
            %td= product.price
            %td= product.created_at.strftime('%Y-%m-%d')
            %td= product.vendor.business_name
            %td
              .commands
                = link_to 'Edit', edit_shopify_product_path(product)
                |
                = link_to 'Delete', shopify_product_path(product, format: :js), method: :delete, remote: true, 'data-confirm' => "Are you sure you want to delete this product?"

app/views/shopify/products/_unbooked_table.html.haml
#shopify-products-table-section
  - unless shopify_products.present?
    %p
      No products to add.
  - else
    %table.table.table-hover.table-striped{'id' => 'unbooked-products-table'}
      %thead
        %th Title
        %th Vendor
        %th 
      %tbody
        - shopify_products.each do |shopify_product|
          %tr{'data-id' => shopify_product.id}
            %td= shopify_product.title
            %td= shopify_product.vendor
            %td
              .commands
                = link_to 'Add', new_shopify_product_path(shopify_product_id: shopify_product.id)

app/views/shopify/products/destroy.js.erb
(function(global) {
  'use strict';
  $('#booked-products-table tr[data-id="<%= @product.id %>"]').fadeOut(function() { 
    $(this).remove(); 
    window.location.reload();
  });
})(window);

app/views/shopify/products/edit.html.haml
- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      ShopifyApp.ready(function() {

        ShopifyApp.Bar.initialize({ 
          title: 'Edit Product',
          breadcrumb: {
            label: "Home",
            href: "#{shopify_root_path}",
            target: 'app',
            loading: false
          } 
        });

        $('#save-product-button').on('click', function(e) {
          e.preventDefault();
          e.stopPropagation();

          var $button = $(this);
          $button.html('Saving...');
          $button.attr('disabled', 'disabled');

          var $form = $('#edit-product-form');
          $form.submit();
        });
      });


    })(window);

.Polaris-Page
  .Polaris-Page__Header.Polaris-Page__Header--hasBreadcrumbs.Polaris-Page__Header--hasSecondaryActions.Polaris-Page__Header--hasSeparator
    .Polaris-Page__MainContent

      .Polaris-Page__TitleAndActions
        .Polaris-Page__Title
          %h1.Polaris-DisplayText.Polaris-DisplayText--sizeLarge 
            Edit Product

      .Polaris-Page__PrimaryAction
        .btn-group
          %button{'type' => 'button', 'class' => 'btn btn-primary', 'id' => 'save-product-button'}
            Save

  .Polaris-Page__Content
    .Polaris-Layout
      .Polaris-Layout__Section
        .container-fluid
          = render partial: 'shopify/products/form', locals: {product: @product, form_url: shopify_product_path(@product), form_html_id: 'edit-product-form'}

app/views/shopify/products/new.html.haml
- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      ShopifyApp.ready(function() {

        ShopifyApp.Bar.initialize({ 
          title: 'New Product',
          breadcrumb: {
            label: "Home",
            href: "#{shopify_root_path(tab: 'products')}",
            target: 'app',
            loading: false
          } 
        });

        $('#save-product-button').on('click', function(e) {
          e.preventDefault();
          e.stopPropagation();

          var $button = $(this);
          $button.html('Saving...');
          $button.attr('disabled', 'disabled');

          var $form = $('#new-product-form');
          $form.submit();
        });
      });


    })(window);

.Polaris-Page
  .Polaris-Page__Header.Polaris-Page__Header--hasBreadcrumbs.Polaris-Page__Header--hasSecondaryActions.Polaris-Page__Header--hasSeparator
    .Polaris-Page__MainContent

      .Polaris-Page__TitleAndActions
        .Polaris-Page__Title
          %h1.Polaris-DisplayText.Polaris-DisplayText--sizeLarge 
            New Product

      .Polaris-Page__PrimaryAction
        .btn-group
          %button{'type' => 'button', 'class' => 'btn btn-primary', 'id' => 'save-product-button'}
            Save

  .Polaris-Page__Content
    .Polaris-Layout
      .Polaris-Layout__Section
        .container-fluid
          = form_for @product, url: shopify_products_path, html: {'id' => 'new-product-form'} do |f|
            = hidden_field_tag :shopify_product_id, @shopify_product.id

            .form-group{'class' => "#{f.object.errors[:vendor].present? ? 'has-error' : ''}"}
              = f.label :vendor_id, 'Vendor', 'class' => ''
              = f.select :vendor_id, current_shop.vendors.all.map { |vendor| [vendor.business_name, vendor.id] }, {}, 'class' => 'form-control', required: true
              - if f.object.errors[:vendor].present?
                %span.help-block= f.object.errors[:vendor].join(', ')


            .form-group
              %label
                Title
              %p.form-control-static 
                = f.object.title


            .form-group{'class' => "#{f.object.errors[:cost_of_goods].present? ? 'has-error' : ''}"}
              = f.label :cost_of_goods, 'Cost of Goods', 'class' => ''
              .input-group
                = f.number_field :cost_of_goods, 'class' => 'form-control'
                %span.input-group-addon
                  USD
              %span.help-block
                this value will be the basis of commision splitting among the vendors.
              - if f.object.errors[:cost_of_goods].present?
                %span.help-block= f.object.errors[:cost_of_goods].join(', ')

            .checkbox
              %label
                = f.check_box :is_bookable
                Is Bookable?
              %span.help-block
                Checking this field will allow a product to have a start and end date booking option.

            #product_timeslots_section.form-group
              .list-group
                - if current_shop.time_slots.unbooked.any?
                  - current_shop.time_slots.unbooked.each do |time_slot|
                    .list-group-item
                      = f.check_box :time_slot_ids, { multiple: true }, time_slot.id
                      = label_tag time_slot.display
                - else
                  %p All TimeSlots are already assigned. Create a new timeslot.

            
            %label= 'Amount that you will keep - the rest goes to the vendor' 
            .form-group{'class' => "#{f.object.errors[:minimum_commission_per_product].present? ? 'has-error' : ''}"}
              .row
                .col-md-2
                  = f.number_field :minimum_commission_per_product, placeholder: '0', 'class' => 'form-control', 'style' => 'width:100%; text-align: right;', 'required' => 'true'
                  - if f.object.errors[:minimum_commission_per_product].present?
                    %span.help-block= f.object.errors[:minimum_commission_per_product].join(', ')
                .col-md-10
                  = f.select :commission_structure_type, [['USD per product or time schedule booking', '$'], ['% per product or time schedule booking', '%']], {}, 'class' => 'form-control', 'style' => 'width:100%;'

- content_for :extra_javascript do
  :javascript
    (function() {
      $(function() {

        $('#product_is_bookable').change(function(e) {
          e.stopPropagation();
          e.preventDefault();
          var checked = $(this).prop('checked');
          if (checked) {
            $('#product_timeslots_section').show();
          } else {
            $('#product_timeslots_section').hide();
          }
        });
        $('#product_is_bookable').change();
      });
    })();