config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: { sessions: 'users/sessions', confirmations: 'users/confirmations' }

  mount ShopifyApp::Engine, at: '/shopify'

  namespace :shopify do

    resources :vendor_invites do
      member do
        delete :cancel
      end
    end

    resources :vendors do
      member do
        patch :change_status
      end
    end

    resources :products

    resources :time_slots
    resources :bookings

    resources :payouts do
      member do
        patch :manual_payment
        patch :stripe_payment
      end
    end

    resource :setting

    resource :admin_user_setup, only: %i[show create]
    resource :payment_setup, only: %i[show]

    root :to => 'home#index'
  end

  resource :vendor_invite_wizard do
    get   :set_password
    patch :set_password
    get   :complete_info
    post  :complete_info
    get   :payment_info
  end

  resource :vendor do
    get :dashboard
    get :calendar
    get :bookings
    get :products
    get :orders
    get :payouts
    get :settings
  end

  resource :admin do
    get :dashboard
  end

  get "/stripe/connect/vendor_connect/callback", to: 'stripe#vendor_connect_callback', as: 'stripe_vendor_connect_callback'
  get "/stripe/connect/admin_connect/callback", to: 'stripe#admin_connect_callback', as: 'stripe_admin_connect_callback'


  post "/stripe/account/webhook", to: 'stripe#account_webhook', as: 'stripe_account_webhook'
  post "/stripe/connect/webhook", to: 'stripe#connect_webhook', as: 'stripe_connect_webhook'

  get "/shopify/scripttags/booking.js", to: 'scripttags#booking', as: 'scripttags_booking_script'
  get "/shopify/scripttags/products/:product_id/info.json", to: 'scripttags#product_info', as: 'scripttags_product_info'
  get "/shopify/scripttags/client_calendar.js", to: 'scripttags#client_calendar', as: 'scripttags_client_calendar_script'
  get "/shopify/scripttags/bookings.json", to: 'scripttags#bookings', as: 'scripttags_bookings_script'

  resources :time_slots

  resources :products do
    get :new
    get :show
    post :create
    patch :update
  end

  resources :orders do
    
  end

  root :to => 'home#index'
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  #--------------------------------------------------------------------
  # Constants
  #--------------------------------------------------------------------
  ACTIVE_STATUS = 'Active'

  #--------------------------------------------------------------------
  # Attributes
  #--------------------------------------------------------------------
  alias_attribute :name, :business_name

  #--------------------------------------------------------------------
  # Associations
  #--------------------------------------------------------------------
  belongs_to :shop
  belongs_to :user, optional: true
  has_many :products
  has_many :bookings
  has_many :payouts

  #--------------------------------------------------------------------
  # Validations
  #--------------------------------------------------------------------
  validates :email, presence: true, 
                    format: { with: URI::MailTo::EMAIL_REGEXP }, 
                    uniqueness: {scope: 'shop_id'}

  validates :business_name, presence: true, uniqueness: {scope: 'shop_id', allow_blank: true}                   
  validates :tax_id, presence: true                   
  validates :poc_first_name, presence: true                   
  validates :poc_last_name, presence: true                   
  validates :phone_number, presence: true
  validates :status, presence: true

  #--------------------------------------------------------------------
  # Scopes
  #--------------------------------------------------------------------
  scope :active, -> { where(:status => ACTIVE_STATUS) }

  #--------------------------------------------------------------------
  # Concerns
  #--------------------------------------------------------------------
  include Concerns::StripeConcern
  include Vendor::ReportDataGeneratorConcern

  #--------------------------------------------------------------------
  # Methods
  #--------------------------------------------------------------------

  def shopify_orders
    self.bookings.map { |booking| booking.shopify_order }
  end

  def unfulfilled_shopify_orders
    shopify_orders.select { |o| o.fulfillment_status.blank? }
  end

  def change_status
    if self.status == "Active"
      self.status = "Inactive"
      self.save
    else
      self.status = "Active"
      self.save
    end
  end
end

app/controllers/shopify/vendors_controller.rb
class Shopify::VendorsController < Shopify::BaseController

  def index
    @vendors = current_shop.vendors
  end

  def new
    @vendor = current_shop.vendors.build
  end

  def create
    @vendor = current_shop.vendors.build(vendor_params)
    if @vendor.save
      redirect_to shopify_root_path'tab' => 'vendors'
      flash.notice = 'Vendor was successfuly created'
    else
      render :new
    end
  end

  def change_status
    @vendor = Vendor.find_by_id(params[:id].to_i)
    @vendor.change_status
    redirect_to shopify_root_path'tab' => 'vendors'
  end

  private

    def vendor_params
      params.require(:vendor).permit(
        :business_name,
        :poc_first_name,
        :poc_last_name,
        :phone_number,
        :email,
        :tax_id,
        :address
      )
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user_in_vendor_role!

  def show
    redirect_to dashboard_vendor_path
  end

  def dashboard
    @unpaid_payouts = current_vendor.payouts.unpaid
    @products = current_vendor.products
    @unfulfilled_orders_count = current_vendor.unfulfilled_shopify_orders.length
    @orders_count = current_vendor.shopify_orders.length
    @products_count = @products.length
    @payouts_paid = ActionController::Base.helpers.number_to_currency(current_vendor.payouts.paid.sum(:amount_to_be_paid_out).round(2))
    @payouts_receivable = ActionController::Base.helpers.number_to_currency(current_vendor.payouts.unpaid.sum(:amount_to_be_paid_out).round(2))
    @total_payouts = ActionController::Base.helpers.number_to_currency(current_vendor.payouts.sum(:amount_to_be_paid_out).round(2))
    @payouts_report_title = Time.zone.now.strftime('%B %Y')
    @payouts_report_data = current_vendor.generate_payouts_report_data
  end

  def calendar

  end

  def bookings
    @bookings = current_vendor.bookings
    respond_to do |format|
      format.json
    end
  end

  def products
    @products = current_vendor.products
  end
  
  def orders
    @orders = current_vendor.shopify_orders
  end
  
  def payouts
    @payouts = current_vendor.payouts
  end
  
  def settings

  end
end

app/helpers/vendor_helper.rb
module VendorHelper

  def vendor_sidebar_active_class(section_name)
    if controller_name == 'vendors' and action_name == section_name.to_s
      'active'
    else
      ''
    end
  end
end

app/views/vendors/_products_table.html.haml
#products-table-section
  - unless products.present?
    %p
      No products yet assigned to you. #{current_shop.shopify_domain} will be the one to assign to you.
  - else
    %table.table.table-hover.table-striped{'id' => 'products-table'}
      %thead
        %th ID
        %th Title
        %th Cost of Goods
        %th Created At
        %th Stocks
        %th Is Bookable?
        %th 
      %tbody
        - products.each do |product|
          %tr{'data-product-id' => product.id}
            %td= product.id
            %td= product.title
            %td= product.cost_of_goods
            %td= product.created_at.strftime('%Y-%m-%d')
            %td= product.inventory_quantity
            %td= product.is_bookable? ? 'yes' : 'no'
            %td
              .commands
                = link_to 'Edit', edit_product_path(product)
                = link_to 'Delete', product_path(product, format: :js), method: :delete, remote: true, 'data-confirm' => "Are you sure you want to delete this product?"

app/views/vendors/calendar.html.haml
%h2.page-title
  Calendar

.row
  .col-md-12
    .card
      .card-body
        #vendor-calendar
    
- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      $(function() {

        $('#vendor-calendar').fullCalendar({
          header: {
            right:  'today month,agendaWeek,listWeek,basicWeek prev,next'
          },
          defaultView: 'agendaWeek',
          slotEventOverlap: false,
          eventSources: [
            {
              url: '#{time_slots_path(format: :json)}',
              color: '#999999',
              textColor: 'black' 
            },
            {
              url: '#{bookings_vendor_path(format: :json)}',
              color: '#76ff03',
              textColor: 'black' 
            }
          ]
        });
      });
      
    })(window);

app/views/vendors/complete_info.html.haml
%h2.page-header
  Complete Your Vendor Info 
  %small
    Vendor Registration Wizard 2 of 3

= render partial: 'shopify/vendors/form', locals: {show_submit: true, vendor: @vendor, form_url: complete_info_vendor_path(@vendor_invite), make_readonly_email: true}

app/views/vendors/dashboard.html.haml
%h2.page-title
  Dashboard


.row.mt-4
  .col-md-4
    .card.card-cascade.narrower
      .view.view-cascade.gradient-card-header.brown.lighten-2
        .card-header-title
          Unfulfilled Orders
      .card-body.card-body-cascade.text-center
        .strong.h1
          = "#{@unfulfilled_orders_count}"

  .col-md-4
    .card.card-cascade.narrower
      .view.view-cascade.gradient-card-header.brown.lighten-2
        .card-header-title
          Order Count
      .card-body.card-body-cascade.text-center
        .strong.h1
          = "#{@orders_count}"

  .col-md-4
    .card.card-cascade.narrower
      .view.view-cascade.gradient-card-header.brown.lighten-2
        .card-header-title
          Product Count
      .card-body.card-body-cascade.text-center
        .strong.h1
          = "#{@products_count}"

.row.mt-4
  .col-md-4
    .card.card-cascade.narrower
      .view.view-cascade.gradient-card-header.brown.lighten-2
        .card-header-title
          Number of Payouts Paid
      .card-body.card-body-cascade.text-center
        .strong.h1
          = "#{@payouts_paid} USD"

  .col-md-4
    .card.card-cascade.narrower
      .view.view-cascade.gradient-card-header.brown.lighten-2
        .card-header-title
          Payouts Received
      .card-body.card-body-cascade.text-center
        .strong.h1
          = "#{@payouts_receivable} USD"

  .col-md-4
    .card.card-cascade.narrower
      .view.view-cascade.gradient-card-header.brown.lighten-2
        .card-header-title
          Total Payouts Paid To Date
      .card-body.card-body-cascade.text-center
        .strong.h1
          = "#{@total_payouts} USD"

.row.mt-4
  .col-md-12
    .card.card-cascade.narrower
      .view.view-cascade.gradient-card-header.brown.lighten-2
        .card-header-title
          Total Revenue
      .card-body.card-body-cascade.text-center
        %canvas{'id' => 'sales-revenue-chart-canvas', 'width' => '100%'}
  
.row.mt-4
  .col-md-12
    .card.card-cascade.narrower
      .view.view-cascade.gradient-card-header.brown.lighten-2
        .card-header-title
          Unpaid Commision Payouts
      .card-body.card-body-cascade.text-center
        - if @unpaid_payouts.present?
          %table.table.table-hover.table-striped{'id' => 'payouts-table'}
            %thead
              %th ID
              %th Product
              %th $ Sold
              %th $ Shop Commision
              %th $ My Commision
              %th Status
            %tbody
              - @unpaid_payouts.each do |payout|
                %tr{'data-id' => payout.id}
                  %td= payout.id
                  %td= (payout.product.title rescue '--removed--')
                  %td= payout.amount_sold
                  %td= payout.amount_commissions_earned
                  %td= payout.amount_to_be_paid_out
                  %td= payout.status.humanize
                  %td
                    - unless payout.is_unpaid?
                      = payout.payment_type.humanize
        - else
          %p Currently there are no unpaid payouts
  
.row.mt-4
  .col-md-12
    .card.card-cascade.narrower
      .view.view-cascade.gradient-card-header.brown.lighten-2
        .card-header-title
          Products
      .card-body.card-body-cascade.text-center
        - if @products.present?
          %table.table.table-hover.table-striped{'id' => 'products-table'}
            %thead
              %th ID
              %th Title
              %th Cost of Goods
              %th Commission
            - @products.each do |product|
              %tr{'data-id' => product.id}
                %td= product.id
                %td= product.title
                %td= "#{ActionController::Base.helpers.number_to_currency(product.cost_of_goods)} USD"
                %td= product.commision_display
        - else
          %p 
            No products currently


- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      var ctx = document.getElementById("sales-revenue-chart-canvas").getContext("2d");
      var myChart = new Chart(ctx, {
          type: 'bar',
          data: {
              labels: [#{@payouts_report_data.map { |d| "'#{j(truncate(d['product_title'], length: 20))}'" }.join(', ').html_safe}],
              datasets: [{
                  label: '#{@payouts_report_title} Revenues',
                  data: [#{@payouts_report_data.map { |d| d['product_paid_out'] }.join(', ')}],
                  backgroundColor: [
                      'rgba(255, 99, 132, 0.2)',
                      'rgba(54, 162, 235, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(75, 192, 192, 0.2)',
                      'rgba(153, 102, 255, 0.2)',
                      'rgba(255, 159, 64, 0.2)'
                  ],
                  borderColor: [
                      'rgba(255,99,132,1)',
                      'rgba(54, 162, 235, 1)',
                      'rgba(255, 206, 86, 1)',
                      'rgba(75, 192, 192, 1)',
                      'rgba(153, 102, 255, 1)',
                      'rgba(255, 159, 64, 1)'
                  ],
                  borderWidth: 1
              }]
          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero:true
                      }
                  }]
              }
          }
      });
    })(window);

app/views/vendors/orders.html.haml
%h2.page-title
  Orders

.row
  .col-md-12
    .card
      .card-body
        = render partial: 'orders/table', locals: {orders: @orders}
    
- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      $(function() {

      });
      
    })(window);

app/views/vendors/payment_info.html.haml
%h2.page-header
  Payment Info
  %small
    Vendor Registration Wizard 3 of 3

%p
  We are using Stripe&trade; to make payments to you. And other info goes here.
%p.text-center
  = connect_vendor_with_stripe_button(@vendor)

app/views/vendors/payouts_history.html.haml
- content_for(:extra_page_title, current_vendor.business_name)
= render partial: 'vendors/side_bar', locals: {menu_selected: :payouts_history}

%h2.page-header
  Payouts History

.row
  .col-md-12
    %table.table.table-hover.table-striped{'id' => 'payouts-table'}
      %thead
        %th ID
        %th Product
        %th $ Sold
        %th $ Shop Commision
        %th $ My Commision
        %th Status
      %tbody
        - @payouts.each do |payout|
          %tr{'data-id' => payout.id}
            %td= payout.id
            %td= (payout.product.title rescue '--removed--')
            %td= payout.amount_sold
            %td= payout.amount_commissions_earned
            %td= payout.amount_to_be_paid_out
            %td= payout.status.humanize
            %td
              - unless payout.is_unpaid?
                = payout.payment_type.humanize
    

- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      
    })(window);

app/views/vendors/products.html.haml
%h2.page-title
  Products

.row
  .col-md-12
    .card
      .card-body
        = render partial: 'products_table', locals: {products: @products, exclude_columns: %i[vendor], hide_commands: true}
    
- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      $(function() {

      });
      
    })(window);

app/views/vendors/settings.html.haml
%h2.page-title
  Settings

.row
  .col-md-12
    .card
      .card-body
    
- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      $(function() {

      });
      
    })(window);