config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: { sessions: 'users/sessions', confirmations: 'users/confirmations' }

  mount ShopifyApp::Engine, at: '/shopify'

  namespace :shopify do

    resources :vendor_invites do
      member do
        delete :cancel
      end
    end

    resources :vendors do
      member do
        patch :change_status
      end
    end

    resources :products

    resources :time_slots
    resources :bookings

    resources :payouts do
      member do
        patch :manual_payment
        patch :stripe_payment
      end
    end

    resource :setting

    resource :admin_user_setup, only: %i[show create]
    resource :payment_setup, only: %i[show]

    root :to => 'home#index'
  end

  resource :vendor_invite_wizard do
    get   :set_password
    patch :set_password
    get   :complete_info
    post  :complete_info
    get   :payment_info
  end

  resource :vendor do
    get :dashboard
    get :calendar
    get :bookings
    get :products
    get :orders
    get :payouts
    get :settings
  end

  resource :admin do
    get :dashboard
  end

  get "/stripe/connect/vendor_connect/callback", to: 'stripe#vendor_connect_callback', as: 'stripe_vendor_connect_callback'
  get "/stripe/connect/admin_connect/callback", to: 'stripe#admin_connect_callback', as: 'stripe_admin_connect_callback'


  post "/stripe/account/webhook", to: 'stripe#account_webhook', as: 'stripe_account_webhook'
  post "/stripe/connect/webhook", to: 'stripe#connect_webhook', as: 'stripe_connect_webhook'

  get "/shopify/scripttags/booking.js", to: 'scripttags#booking', as: 'scripttags_booking_script'
  get "/shopify/scripttags/products/:product_id/info.json", to: 'scripttags#product_info', as: 'scripttags_product_info'
  get "/shopify/scripttags/client_calendar.js", to: 'scripttags#client_calendar', as: 'scripttags_client_calendar_script'
  get "/shopify/scripttags/bookings.json", to: 'scripttags#bookings', as: 'scripttags_bookings_script'

  resources :time_slots

  resources :products do
    get :new
    get :show
    post :create
    patch :update
  end

  resources :orders do
    
  end

  root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout false

  before_action :redirect_to_dashboard_according_to_user_role, only: %i[index]

  def index
  end

  private

    def redirect_to_dashboard_according_to_user_role
      if is_user_role_vendor?
        redirect_to dashboard_vendor_path
      elsif is_user_role_admin?
        redirect_to dashboard_admin_path
      end
    end
end

app/controllers/shopify/admin_user_setups_controller.rb
class Shopify::AdminUserSetupsController < Shopify::BaseController

  skip_before_action :check_prerequisites!

  def show
    @user = current_shop.users.build({
      email: current_shop.shopify_session { ShopifyAPI::Shop.current.email },
      role: User::ADMIN_ROLE
    }) 
  end

  def create
    @user = current_shop.users.build({
      email: current_shop.shopify_session { ShopifyAPI::Shop.current.email },
      role: User::ADMIN_ROLE,
      password: user_params[:password],
      password_confirmation: user_params[:password_confirmation]    
    })
    @user.validate_password!
    @user.skip_confirmation!
    if @user.save
      current_shop.update_column(:admin_user_id, @user.id)
      redirect_to shopify_root_path
    else
      render :show
    end 
  end

  private

    def user_params
      params.require(:user).permit(
        :password,
        :password_confirmation
      )
    end
end

app/controllers/shopify/base_controller.rb
class Shopify::BaseController < ShopifyApp::AuthenticatedController

  before_action :check_prerequisites!

  helper :all
  helper_method :current_shop

  protected

    def current_shop
      Shop.find_by_shopify_domain!(current_shopify_domain)
    end

  private

    def check_prerequisites!
      if current_shop.has_no_admin_user?
        redirect_to shopify_admin_user_setup_path
      elsif not current_shop.has_payment_info?
        redirect_to shopify_payment_setup_path
      end
    end
end

app/controllers/shopify/bookings_controller.rb
class Shopify::BookingsController < Shopify::BaseController

  def index
    @bookings = current_shop.bookings
  end
end

app/controllers/shopify/home_controller.rb
class Shopify::HomeController < Shopify::BaseController

  def index
  	@active_vendors = current_shop.vendors.active
  	@new_time_slot = current_shop.time_slots.build
    @new_product = current_shop.products.build
    @vendor_invites = current_shop.vendor_invites
    @vendors = current_shop.vendors
    @products = current_shop.products
    @unbooked_shopify_products = current_shop.unbooked_shopify_products
    @booked_shopify_products = current_shop.booked_shopify_products
    @payouts = current_shop.payouts.includes(:vendor)

    @sales_total = current_shop.payouts.sum(:amount_sold)
    @commission_total = current_shop.payouts.sum(:amount_commissions_earned)

    @payouts_unpaid = current_shop.payouts.unpaid.sum(:amount_to_be_paid_out)
    @payouts_paid = current_shop.payouts.paid.sum(:amount_to_be_paid_out)
    @payouts_total = current_shop.payouts.sum(:amount_to_be_paid_out)

    @product_sales_title = "#{Time.zone.now.strftime('%B %Y')} Product Sales"
    @product_sales_report_data = current_shop.generate_product_sales_report_data

    @product_commissions_earned_title = "#{Time.zone.now.strftime('%B %Y')} Product Commissions Earned"
    @product_commissions_earned_report_data = current_shop.generate_product_commissions_earned_report_data
  end
end

app/controllers/shopify/payment_setups_controller.rb
class Shopify::PaymentSetupsController < Shopify::BaseController

  skip_before_action :check_prerequisites!

  def show
  end

  private
end

app/controllers/shopify/payouts_controller.rb
class Shopify::PayoutsController < Shopify::BaseController
	  
  before_action :set_payout, only: %i[manual_payment stripe_payment]

  def manual_payment
    @payout.manual_payment!
    respond_to do |format|
      format.js
    end
  end

  def stripe_payment
    @payout.stripe_payment!
    respond_to do |format|
      format.js
    end
  end

  private

    def set_payout
      @payout = current_shop.payouts.find(params[:id])
    end
end

app/controllers/shopify/products_controller.rb
class Shopify::ProductsController < Shopify::BaseController
	
  before_action :set_product, only: %i[show edit update destroy]
  before_action :set_shopify_product, only: %i[new create]

  def new
    @product = current_shop.products.build
    @product.set_shopify_product!(@shopify_product)
  end

	def create
		@product = current_shop.products.build(product_params)
    @product.set_shopify_product!(@shopify_product)
		if @product.save
			redirect_to shopify_root_path(tab: 'products')
			flash[:notice] = 'Product was successfully added'
		else
			render :new
		end
	end

  def show
    render :edit
  end

  def edit

  end

  def update
    if @product.update_attributes(product_params)
      redirect_to shopify_root_path(tab: 'products')
      flash[:notice] = 'Product was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy!
    respond_to do |format|
      format.js
    end
  end

	private

    def set_product
      @product = current_shop.products.find(params[:id])
    end
  
  	def product_params
  		params.require(:product).permit(
        :vendor_id,
        :title,
  			:cost_of_goods,
  			:minimum_commission_per_product,
  			:commission_structure_type,
        :is_bookable,
        time_slot_ids: []
  		)
  	end		

    def shopify_product_id
      params[:shopify_product_id]
    end

    def set_shopify_product
      @shopify_product = current_shop.find_shopify_product(shopify_product_id)
    end
end

app/controllers/shopify/settings_controller.rb
class Shopify::SettingsController < Shopify::BaseController

	def update
		@setting = current_shop.setting
		if @setting.update_attributes(setting_params)
			redirect_to shopify_root_path('tab' => 'settings')
			flash.notice = 'Settings successfully updated'
		end
	end

	private 

	  def setting_params
		  params.require(:setting).permit(
			  :shop_id,
			  :minimum_commission_per_product,
			  :structure_type
		  )
	  end
end

app/controllers/shopify/time_slots_controller.rb
class Shopify::TimeSlotsController < Shopify::BaseController

  before_action :set_time_slot, only: %i[show edit update destroy]

  def index
    @time_slots = current_shop.time_slots

    respond_to do |format|
      format.json
    end
  end

  def new
    @time_slot = current_shop.time_slots.build
  end

  def create
    @time_slot = current_shop.time_slots.build(time_slot_params)
    if @time_slot.save
      flash.notice = 'Timeslot was successfuly created'
      redirect_to shopify_root_path 'tab' => 'calendar'
    else
      render :new
    end
  end

  def show
    redirect_to edit_shopify_time_slot_path(@time_slot)
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    if @time_slot.update_attributes(time_slot_params)
      flash.notice = 'Timeslot was successfuly updated'
      redirect_to shopify_root_path 'tab' => 'calendar'
    else
      render :edit
    end
  end

  def destroy
    @time_slot.destroy!
    flash.notice = 'Timeslot was successfuly destroyed'
    redirect_to shopify_root_path 'tab' => 'calendar'
  end

  private

    def set_time_slot
      @time_slot = current_shop.time_slots.find(params[:id])
    end

    def time_slot_params
      params.require(:time_slot).permit(
        :description,
        :start_date,
        :start_time,
        :end_date,
        :end_time
        #:is_all_day
      )
    end
end

app/controllers/shopify/vendor_invites_controller.rb
class Shopify::VendorInvitesController < Shopify::BaseController

  before_action :set_vendor_invite, only: %w[cancel]

  def index
    @vendor_invites = current_shop.vendor_invites
  end

  def new
    @vendor_invite = current_shop.vendor_invites.build
  end

  def create
    @vendor_invite = current_shop.vendor_invites.build(vendor_invite_params)
    if @vendor_invite.save
      redirect_to shopify_root_path('tab' => 'vendor_invites')
      flash.notice = "Invitation for vendor was sent to #{@vendor_invite.email}."
    else
      render :new
    end
  end

  def cancel
    if @vendor_invite.can_cancel?
      @vendor_invite.cancel!
      @vendor_invites = current_shop.vendor_invites
      respond_to do |format|
        format.js
      end
    else
      @vendor_invites = current_shop.vendor_invites
      respond_to do |format|
        format.js
      end
    end
  end

  private

    def set_vendor_invite
      @vendor_invite = current_shop.vendor_invites.find(params[:id])
    end

    def vendor_invite_params
      params.require(:vendor_invite).permit(
        :email
      )
    end
end

app/controllers/shopify/vendors_controller.rb
class Shopify::VendorsController < Shopify::BaseController

  def index
    @vendors = current_shop.vendors
  end

  def new
    @vendor = current_shop.vendors.build
  end

  def create
    @vendor = current_shop.vendors.build(vendor_params)
    if @vendor.save
      redirect_to shopify_root_path'tab' => 'vendors'
      flash.notice = 'Vendor was successfuly created'
    else
      render :new
    end
  end

  def change_status
    @vendor = Vendor.find_by_id(params[:id].to_i)
    @vendor.change_status
    redirect_to shopify_root_path'tab' => 'vendors'
  end

  private

    def vendor_params
      params.require(:vendor).permit(
        :business_name,
        :poc_first_name,
        :poc_last_name,
        :phone_number,
        :email,
        :tax_id,
        :address
      )
    end
end

app/helpers/home_helper.rb
module HomeHelper

  def shopify_home_tab_active_class(tab_name, options={})
    the_options = options.with_indifferent_access
    css_active_class = the_options[:active] || 'active'
    css_inactive_class = the_options[:inactive] || ''
    css_class_name = case tab_name
    when :dashboard 
      (params[:tab].blank? || params[:tab] == tab_name.to_s) ? css_active_class : css_inactive_class 
    else
      (params[:tab] == tab_name.to_s) ? css_active_class : css_inactive_class 
    end
    css_class_name
  end
end

app/helpers/shopify/payouts_helper.rb
module Shopify::PayoutsHelper
end

app/helpers/shopify/products_helper.rb
module Shopify::ProductsHelper
end

app/helpers/shopify/settings_helper.rb
module Shopify::SettingsHelper
end

app/views/shopify/home/_active_vendors_table.html.haml
- unless @active_vendors.present?
  %p
    You have no active vendors
- else  
  %table.table.table-hover.table-striped
    %thead
      %th ID
      %th Name
      %th Created At
      %th Status
    %tbody
      - @active_vendors.each do |vendor|
        %tr
          %td= vendor.id
          %td= vendor.name
          %td= vendor.created_at.strftime('%b %-d, %Y')
          %td= vendor.status

app/views/shopify/home/_dashboard.html.haml
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Sales Total
      .panel-body
        .text-center
          .strong.h1
            = "#{@sales_total} USD"

  .col-md-6
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Commission Total
      .panel-body
        .text-center
          .strong.h1
            = "#{@commission_total} USD"

.row
  .col-md-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Unpaid Payouts
      .panel-body
        .text-center
          .strong.h1
            = "#{@payouts_unpaid} USD"

  .col-md-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Paid Payouts
      .panel-body
        .text-center
          .strong.h1
            = "#{@payouts_paid} USD"
      
  .col-md-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Total Payouts
      .panel-body
        .text-center
          .strong.h1
            = "#{@payouts_total} USD"


.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Product Sales
      .panel-body
        %canvas{'id' => 'product-sales-chart-canvas', 'width' => '100%'}


.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Product Commissions Earned
      .panel-body
        %canvas{'id' => 'product-commissions-earned-chart-canvas', 'width' => '100%'}


.row
  .col-md-12  
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Commision Payouts
      .panel-body
        = render partial: 'shopify/home/payouts_table'
.row
  .col-md-12  
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          Active Vendors
      .panel-body
        = render partial: 'shopify/home/active_vendors_table'

- content_for(:extra_javascript) do
  :javascript
    (function(global) {
      'use strict';

      var ctx = document.getElementById("product-sales-chart-canvas").getContext("2d");
      var myChart = new Chart(ctx, {
          type: 'bar',
          data: {
              labels: [#{@product_sales_report_data.map { |d| "'#{j(truncate(d['product_title'], length: 20))}'" }.join(', ').html_safe}],
              datasets: [{
                  label: '#{@product_sales_title}',
                  data: [#{@product_sales_report_data.map { |d| d['product_amount_sold'] }.join(', ')}],
                  backgroundColor: [
                      'rgba(255, 99, 132, 0.2)',
                      'rgba(54, 162, 235, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(75, 192, 192, 0.2)',
                      'rgba(153, 102, 255, 0.2)',
                      'rgba(255, 159, 64, 0.2)'
                  ],
                  borderColor: [
                      'rgba(255,99,132,1)',
                      'rgba(54, 162, 235, 1)',
                      'rgba(255, 206, 86, 1)',
                      'rgba(75, 192, 192, 1)',
                      'rgba(153, 102, 255, 1)',
                      'rgba(255, 159, 64, 1)'
                  ],
                  borderWidth: 1
              }]
          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero:true
                      }
                  }]
              }
          }
      });
    })(window);

  :javascript
    (function(global) {
      'use strict';

      var ctx = document.getElementById("product-commissions-earned-chart-canvas").getContext("2d");
      var myChart = new Chart(ctx, {
          type: 'bar',
          data: {
              labels: [#{@product_commissions_earned_report_data.map { |d| "'#{j(truncate(d['product_title'], length: 20))}'" }.join(', ').html_safe}],
              datasets: [{
                  label: '#{@product_commissions_earned_title}',
                  data: [#{@product_commissions_earned_report_data.map { |d| d['product_amount_commissions_earned'] }.join(', ')}],
                  backgroundColor: [
                      'rgba(255, 99, 132, 0.2)',
                      'rgba(54, 162, 235, 0.2)',
                      'rgba(255, 206, 86, 0.2)',
                      'rgba(75, 192, 192, 0.2)',
                      'rgba(153, 102, 255, 0.2)',
                      'rgba(255, 159, 64, 0.2)'
                  ],
                  borderColor: [
                      'rgba(255,99,132,1)',
                      'rgba(54, 162, 235, 1)',
                      'rgba(255, 206, 86, 1)',
                      'rgba(75, 192, 192, 1)',
                      'rgba(153, 102, 255, 1)',
                      'rgba(255, 159, 64, 1)'
                  ],
                  borderWidth: 1
              }]
          },
          options: {
              scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero:true
                      }
                  }]
              }
          }
      });
    })(window);

app/views/shopify/home/_payouts_table.html.haml
- unless @payouts.present?
  %p
    You haven't made a payout yet.
- else
  = render partial: 'shopify/payouts/table', locals: {payouts: @payouts}

app/views/shopify/home/index.html.haml
- content_for(:extra_javascript) do
  :javascript
    (function() {
      'use strict';

      ShopifyApp.ready(function() {
        
        ShopifyApp.Bar.initialize({
          title: 'Dashboard'
        });

        $('#dashboard-tabs a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
          var $newTab = $(e.target);
          
          $('.tab-btn-groups .btn-group').addClass('hidden');
          $($newTab.attr('href').replace('-pane', '-btn-group')).removeClass('hidden');

          if ($newTab.attr('href') == '#calendar-tab-pane') {
            setTimeout(function() {
              $('#slot-calendar').fullCalendar('render');
              setTimeout(function() {
                $('#slot-calendar').fullCalendar('changeView', 'month');
                $('#slot-calendar').fullCalendar('changeView', 'agendaWeek');
              }, 100);
            }, 100);
          }
        });

        $('#slot-calendar').fullCalendar({
          header: {
            right:  'today month,agendaWeek,listWeek,basicWeek prev,next'
          },
          slotEventOverlap: false,
          defaultView: 'agendaWeek',
          eventSources: [
            {
              url: '#{shopify_time_slots_path(format: :json)}',
              color: '#999999',
              textColor: 'black' 
            },
            {
              url: '#{shopify_bookings_path(format: :json)}',
              color: '#76ff03',
              textColor: '#000' 
            }
          ],
          eventClick: function(calEvent, jsEvent, view) {
            if (calEvent.className == 'booking') {
              var url = calEvent.order_status_url;
              window.open(url);
            } else {
              var $editDialog = $('#edit-time-slot-dialog');
              $editDialog.data('calEvent', calEvent);
              $editDialog.modal({

              });
            }
          },
          eventMouseover: function(calEvent, jsEvent, view) {
            if (calEvent.className == 'booking') {
              $(this).css({
                'background-color': '#005005',
                'color': '#CCC'
              });
            } else {
              $(this).css({
                'background-color': '#333',
                'color': '#CCC'
              });
            }
          },
          eventMouseout: function(calEvent, jsEvent, view) {
            if (calEvent.className == 'booking') {
              $(this).css({
                'background-color': '#76ff03',
                'color': '#000'
              });
            } else {
              $(this).css({
                'background-color': '#999',
                'color': '#000'
              });
            }
          }
        });

        $('#save-setting-form-button').on('click', function(e) {
          e.preventDefault();
          e.stopPropagation();

          var $btn = $(e.target);
          $btn.prop('disabled', true);
          $btn.html('Saving...');

          $('#setting-form').submit();
        });

        $('#new-product-command').on('click', function(e) {
          e.preventDefault();
          e.stopPropagation();

          ShopifyApp.redirect("/admin/products/new");
        });
      });
    })();

.Polaris-Page
  .Polaris-Page__Header.Polaris-Page__Header--hasBreadcrumbs.Polaris-Page__Header--hasSecondaryActions.Polaris-Page__Header--hasSeparator
    .Polaris-Page__MainContent
      
      .Polaris-Page__TitleAndActions
        .Polaris-Page__Title
          %h1.Polaris-DisplayText.Polaris-DisplayText--sizeLarge 
            Creative Den Dashboard
      
      .Polaris-Page__PrimaryAction
        .tab-btn-groups

          .btn-group#dashboard-tab-btn-group{'class' => shopify_home_tab_active_class(:dashboard, inactive: 'hidden')}
            %button{'type' => 'button', 'class' => 'btn btn-primary', 'data-toggle' => 'modal', 'data-target' => '#invite-vendor-dialog'}
              Invite a Vendor

          
          .btn-group#calendar-tab-btn-group{'class' => shopify_home_tab_active_class(:calendar, inactive: 'hidden')}
            %button{'type' => 'button', 'class' => 'btn btn-primary', 'data-toggle' => 'modal', 'data-target' => '#new-time-slot-dialog'}
              Create New TimeSlot

          .btn-group#vendor-invites-tab-btn-group{'class' => shopify_home_tab_active_class(:vendor_invites, inactive: 'hidden')}
            %button{'type' => 'button', 'class' => 'btn btn-primary', 'data-toggle' => 'modal', 'data-target' => '#invite-vendor-dialog'}
              Invite a Vendor

          .btn-group#vendors-tab-btn-group{'class' => shopify_home_tab_active_class(:vendors, inactive: 'hidden')}
            %a{'class' => 'btn btn-primary', 'href' => '#new-vendor-dialog', 'data-toggle' => 'modal', 'data-target' => '#new-vendor-dialog'}
              Create New Vendor
            %button{'type' => 'button', 'class' => 'btn btn-primary dropdown-toggle', 'data-toggle' => 'dropdown', 'aria-haspopup' => 'true', 'aria-expanded' => 'false'}           
              %span.caret
              %span.sr-only
                More Actions
            %ul.dropdown-menu
              %li
                %a{'href' => '#invite-vendor-dialog', 'data-toggle' => 'modal', 'data-target' => '#invite-vendor-dialog'}
                  Invite a Vendor

          - if current_shop.vendors.any?
            .btn-group#products-tab-btn-group{'class' => shopify_home_tab_active_class(:products, inactive: 'hidden')}
              -# %button{'type' => 'button', 'class' => 'btn btn-primary', 'data-toggle' => 'modal', 'data-target' => '#new-product-dialog'}
              -#   Create New Product
              %button{'type' => 'button', 'class' => 'btn btn-primary', 'id' => 'new-product-command'}
                Create New Product or Class

          .btn-group#settings-tab-btn-group{'class' => shopify_home_tab_active_class(:settings, inactive: 'hidden')}
            %button{'type' => 'button', 'class' => 'btn btn-primary', id: 'save-setting-form-button'}
              Save

  .Polaris-Page__Content
    .Polaris-Layout
      .Polaris-Layout__Section
        .container-fluid
          
          %ul.nav.nav-tabs{'role' => 'tablist', 'id' => 'dashboard-tabs'}
            %li{'role' => 'presentation', 'class' => shopify_home_tab_active_class(:dashboard)}
              %a{'href' => '#dashboard-tab-pane', 'aria-controls' => 'classes', 'role' => 'tab', 'data-toggle' => 'tab'}
                Dashboard

            %li{'role' => 'presentation', 'class' => shopify_home_tab_active_class(:calendar)}
              %a{'href' => '#calendar-tab-pane', 'aria-controls' => 'calendar', 'role' => 'tab', 'data-toggle' => 'tab'}
                Calendar

            %li{'role' => 'presentation', 'class' => shopify_home_tab_active_class(:vendor_invites)}
              %a{'href' => '#vendor-invites-tab-pane', 'aria-controls' => 'vendor-invites', 'role' => 'tab', 'data-toggle' => 'tab'}
                Vendor Invites

            %li{'role' => 'presentation', 'class' => shopify_home_tab_active_class(:vendors)}
              %a{'href' => '#vendors-tab-pane', 'aria-controls' => 'vendors', 'role' => 'tab', 'data-toggle' => 'tab'}
                Vendors
            
            - if current_shop.vendors.any?
              %li{'role' => 'presentation', 'class' => shopify_home_tab_active_class(:products)}
                %a{'href' => '#products-tab-pane', 'aria-controls' => 'products', 'role' => 'tab', 'data-toggle' => 'tab'}
                  Product or Class

            %li{'role' => 'presentation', 'class' => shopify_home_tab_active_class(:settings)}
              %a{'href' => '#settings-tab-pane', 'aria-controls' => 'settings', 'role' => 'tab', 'data-toggle' => 'tab'}
                Settings
          
          .tab-content
            
            .tab-pane{'id' => 'dashboard-tab-pane', 'role' => 'tabpanel', 'class' => shopify_home_tab_active_class(:dashboard)}
              = render partial: 'shopify/home/dashboard'
            
            .tab-pane{'id' => 'calendar-tab-pane', 'role' => 'tabpanel', 'class' => shopify_home_tab_active_class(:calendar)}
              #slot-calendar
            
            .tab-pane{'id' => 'vendor-invites-tab-pane', 'role' => 'tabpanel', 'class' => shopify_home_tab_active_class(:vendor_invites)}
              = render partial: 'shopify/vendor_invites/table', locals: {vendor_invites: @vendor_invites}
            
            .tab-pane{'id' => 'vendors-tab-pane', 'role' => 'tabpanel', 'class' => shopify_home_tab_active_class(:vendors)}
              = render partial: 'shopify/vendors/table', locals: {vendors: @vendors}

            - if current_shop.vendors.any?
              .tab-pane{'id' => 'products-tab-pane', 'role' => 'tabpanel', 'class' => shopify_home_tab_active_class(:products)}
                .panel
                  .panel-heading
                    %h4 Not Added
                  .panel-body
                    = render partial: 'shopify/products/unbooked_table', locals: {shopify_products: @unbooked_shopify_products}
                    .panel
                  .panel-heading
                    %h4 Added
                  .panel-body
                    = render partial: 'shopify/products/booked_table', locals: {shopify_products: @booked_shopify_products}
            
            .tab-pane{'id' => 'settings-tab-pane', 'role' => 'tabpanel', 'class' => shopify_home_tab_active_class(:settings)}
              = render partial: 'shopify/settings/index' 
              

- content_for(:extra_html) do 
  = render partial: 'shopify/time_slots/new_dialog' 
  = render partial: 'shopify/time_slots/edit_dialog' 
  = render partial: 'shopify/vendor_invites/new_dialog' 
  - if current_shop.vendors.any?
    = render partial: 'shopify/products/new_dialog'    